# Generated by Django 3.1.5 on 2021-01-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.bucket')),
            ],
        ),
    ]
